project:
  type: website
  output-dir: _site
  resources:
    - "resume.pdf"
website:
  title: "Akhilesh"
  navbar:
    left:
      - about.qmd
      - teaching.qmd
      - icon: rss
        href: index.xml
  page-footer:
    center:
      - text: "About"
        href: about.qmd

      - icon: github
        href: https://github.com/akki2825/akki2825.github.io
        aria-label: Quarto GitHub
      - icon: twitter
        href: https://x.com/Akhilesh_k_r
        aria-label: Quarto Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/akhilesh-kr/
        aria-label: Quarto LinkedIn

format:
  html:
    theme: default
    css: styles.css
    include-in-header: "plausible.html"
