---
layout: post
title: "Installing Aeneas on WSL and MacOS"
categories: [computer-science, nlp]
author: "Akhilesh"
date: "2021-12-07"
---
An installation guide.

This is a detailed guide to install Aeneas (<https://github.com/akki2825/aeneas>) that supports python3.6+ on Windows Subsystem for Linux (WSL) and MacOS.


## Windows Subsystem for Linux (WSL)

- Go to Search bar on the bottom left of the screen (next to the Windows icon) and search for `Command Prompt`. Right click on `Command Prompt` icon and select `Run as administrator`. This should open the command prompt.

- Type `wsl --install` and press `Enter`. If you run into any errors, it is most likely the case that your windows version doesn't support WSL or you're internet is unstable.

- The above process might take a few minutes. Once done, go to your browser and type `https://aka.ms/wslstore` and press `Enter`.

- Once the above webpage loads, scroll a bit down and click on `Ubuntu`. Subsequently click on `Get` and `Install`.

- Once the `Ubuntu` application opens, enter a username and password that you can frequently remember.

Copy and Paste (right-click on the terminal to paste) the below code:

```
sudo apt-get update
sudo apt-get upgrade
```

### Easy Installation

Download the script from here (<https://gist.github.com/akki2825/3b38a9f33170b31617b141e53745565b>) and run this shell script using:

```
git clone https://gist.github.com/akki2825/3b38a9f33170b31617b141e53745565b
cd 3b38a9f33170b31617b141e53745565b/
sh install_py3_aeneas.sh
```

### Detailed Installation

**Clone the py3-aeneas repository**

```
git clone https://github.com/akki2825/aeneas
cd aeneas/
```

**Install system dependencies**

```
sudo apt-get install -y python3-dev
sudo apt-get install python3-pip
sudo apt-get install make autoconf automake libtool pkg-config
sudo apt-get install libespeak-dev
sudo apt-get install ffmpeg
sudo apt-get install espeak
sudo apt-get install espeak-data
```

**Install Python packages**

```
sudo pip3 install numpy
sudo pip3 install py3-aeneas
```

**Compile Python C/C++ extensions**

```
sudo python3 setup.py build_ext --inplace
```

**Check Setup**

```
sudo python3 -m aeneas.diagnostics
```

## MacOS

Copy and Paste the below code in the terminal (using Command+C and Command+V):

**Install Brew**

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```


### Easy Installation

Download the script from here (<https://gist.github.com/akki2825/8014a2800eaf638eee2989974655c98f>) and run this shell script using:

```
git clone https://gist.github.com/akki2825/8014a2800eaf638eee2989974655c98f
cd 8014a2800eaf638eee2989974655c98f/
sh install_py3_aeneas.sh
```


### Detailed installation

**Clone the py3-aeneas repository**

```
git clone https://github.com/akki2825/aeneas
cd aeneas/
```

**Install system dependencies**

```
brew install python3
brew install python3-dev
brew install python3-pip
brew install ffmpeg
brew install espeak
brew install espeak-data
```


**Install Python packages**

```
sudo pip3 install numpy
sudo pip3 install py3-aeneas
```

**Compile Python C/C++ extensions**

```
sudo python3 setup.py build_ext --inplace
```

**Check Setup**

```
sudo python3 -m aeneas.diagnostics
```

