---
layout: post
title: "U.S Government's take on FOSS (Free and Open Source Software)"
categories: [computer-science]
author: "Akhilesh"
date: "2020-05-29"
---

> Free software is software that respects your freedom.

This is a running blog on how the U.S government *uses* and *advocates* Free and Open Source Software.

The [US Department of Defence's (DoD) OSS FAQ](https://dodcio.defense.gov/Open-Source-Software-FAQ/) states, "continuous and broad peer-review, enabled by publicly available source code, improves software reliability and security through the identification and elimination of defects that might otherwise go unrecognized".

From the [DoD Software Acquisition and Practices (SWAP) study](https://innovation.defense.gov/software/): "DoD should use open source when possible to speed development and deployment and leverage the work of others".

[Digital Service Playbook](https://playbook.cio.gov/) was developed by U.S Digital Service and outlines several best practices from the private sector that can help the Government build effective digital services.

[Federal Source Code Policy](https://sourcecode.cio.gov/): "requires agencies, when commissioning new custom software, to release at least 20 percent of new custom-developed code as Open Source Software (OSS)".


Here are a few agencies that have embraced the Federal Source Code Policy:

- [Social Security Administration (SSA)](https://www.ssa.gov/digitalstrategy/m_16_21_Implementation_Plan.html)
- [GSA Open Source Software Policy](https://www.gsa.gov/directives-library/gsa-open-source-software-oss-policy-21071-cio)
- [NASA Federal Source Code Framework](https://code.nasa.gov/NASA-M-16-21-Framework.pdf)
- [EPA: Interim Open Source Software (OSS)](https://www.epa.gov/open/interim-open-source-software-oss-policy)
- [https://code.gov](https://code.gov)
